### PR TITLE
Add git attributes & ignore

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Normalize on the line-endings (or avoid any problems with those, if
possible). All content here is for Linux only, so not that likely though.

Git ignore-file to avoid any accidental additions of the delta-files
created (.tar.gz).

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
@ygoyal18  @cmonr @petedyerarm  - please review.

**Review by petedyerarm — APPROVED** [review]
LGTM

**Review by ygoyal18 — APPROVED** [review]
LGTM

**Comment by ygoyal18** [comment]
@JanneKiiskila Please rebase to dev. Similar dev process is followed as meta layers - PRs first goes to dev and then we release to master.

**Comment by JanneKiiskila** [comment]
Obsolete, see https://github.com/PelionIoT/scripts-pelion-edge/pull/29. (based on dev).

**Pull request closed without merging**
