### PR TITLE
UX - clean out legacy scripts to legacy-yocto folder

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Seems customers do get confused with the scripts in the root and try to use them
quite frequently with the LmP / OSTree based updates and then have various issues.

Let us make it more explicit what the choices are and where those are located.

https://armiot.atlassian.net/browse/PELEDGE19-4857

### CODE REVIEW

**Comment by AnotherButler** [comment]
@JanneKiiskila Please review my changes to make sure I didn't accidentally change the meaning of anything (specifically the content in the bullets).

**Comment by JanneKiiskila** [comment]
Looks fine to me.

**Comment by JanneKiiskila** [comment]
@x85446  @petedyerarm  @whygoyal  - please review.

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by JanneKiiskila** [comment]
@mohitsingalarm - do you have any tests on the old legacy Yocto running, that could be impacted by this?

**Pull request merged**
