### PR TITLE
protects var/run softlinking

### PR DESCRIPTION
**Pull request by x85446**

### CODE REVIEW

**Comment by cmonr** [comment]
Whaaaat? This was a problem?

**Review by ygoyal18 — APPROVED** [review]
LGTM.

**Comment by ygoyal18** [comment]
> Whaaaat? This was a problem?

Yes. Out of factory /var/run is symlinked to /run folder. But the delta image overwrote the /var/run folder and deleted the symlink. This in turn caused kubelet to fail because docker by defaults (don't know why) creates a UDS in /run/docker.sock which due to symlink can be found also at /var/run/docker.sock which is where kubelet was expecting it to be.

**Comment by cmonr** [comment]
Woah, good catch.

Might also be worth making sure the delta _can't_ overwrite critical directories, or expanding this blacklist file to cover standard top-level folders.

**Pull request merged**
